# action.yml
name: 'Giphy PR Comment'
description: 'Add a Giphy GIF comment to new pull requests .'
inputs:
  github-token:  # id of input
    description: 'Github Token'
    required: true
  giphy-api-key:  # id of input
    description: 'Giphy API key'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'